// <auto-generated />
using MVCConcesionaria.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVCConcesionaria.Migrations
{
    [DbContext(typeof(ConcesionariaDatabaseContext))]
    [Migration("20221024162453_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVCConcesionaria.Models.Auto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("cantKm")
                        .HasColumnType("float");

                    b.Property<int>("cantPuertas")
                        .HasColumnType("int");

                    b.Property<bool>("esUsado")
                        .HasColumnType("bit");

                    b.Property<string>("marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modelo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Autos");
                });

            modelBuilder.Entity("MVCConcesionaria.Models.Camioneta", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("cantKm")
                        .HasColumnType("float");

                    b.Property<bool>("es4x4")
                        .HasColumnType("bit");

                    b.Property<bool>("esDobleCabina")
                        .HasColumnType("bit");

                    b.Property<bool>("esUsado")
                        .HasColumnType("bit");

                    b.Property<string>("marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modelo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Camionetas");
                });

            modelBuilder.Entity("MVCConcesionaria.Models.Moto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<double>("cantKm")
                        .HasColumnType("float");

                    b.Property<bool>("esUsado")
                        .HasColumnType("bit");

                    b.Property<string>("marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modelo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Motos");
                });
#pragma warning restore 612, 618
        }
    }
}
